experiments:
  exp01_baseline:
    description: "Unguided baseline on QM9-CHON, matched sampler settings."
    dataset: {name: qm9_chon, split: test, limit: 0}
    seed: 42
    model: {ckpt: null, steps: 5, guidance: {enabled: false, weight: 0.0, policy: additive}}
    ai: {scorer: surrogate, surrogate_ckpt: dummy, grammar: default, calibration: {n_mols: 0}}
    sampler: {n_samples: 10, batch_size: 4}
    metrics: {rdkit: true, novelty: true, uniqueness: true, diversity: internal_tanimoto}
    artifacts: {save_smiles: true, save_sdf: false, save_ai_scores: true}

  exp02_guided_lambda1:
    description: "Guided run, λ=1.0, exact AI."
    dataset: {name: qm9_chon, split: test, limit: 0}
    seed: 42
    model: {ckpt: null, steps: 5, guidance: {enabled: true, weight: 1.0, policy: additive}}
    ai: {scorer: exact, surrogate_ckpt: null, grammar: default, calibration: {n_mols: 0}}
    sampler: {n_samples: 10, batch_size: 4}
    metrics: {rdkit: true, novelty: true, uniqueness: true, diversity: internal_tanimoto}
    artifacts: {save_smiles: true, save_sdf: false, save_ai_scores: true}

  exp03_guided_lambda0p5:
    description: "Guided run, λ=0.5, exact AI."
    dataset: {name: qm9_chon, split: test, limit: 0}
    seed: 42
    model: {ckpt: null, steps: 5, guidance: {enabled: true, weight: 0.5, policy: additive}}
    ai: {scorer: exact, surrogate_ckpt: null, grammar: default, calibration: {n_mols: 0}}
    sampler: {n_samples: 10, batch_size: 4}
    metrics: {rdkit: true, novelty: true, uniqueness: true, diversity: internal_tanimoto}
    artifacts: {save_smiles: true, save_sdf: false, save_ai_scores: true}

  exp04_guided_lambda2:
    description: "Guided run, λ=2.0, exact AI."
    dataset: {name: qm9_chon, split: test, limit: 0}
    seed: 42
    model: {ckpt: null, steps: 5, guidance: {enabled: true, weight: 2.0, policy: additive}}
    ai: {scorer: exact, surrogate_ckpt: null, grammar: default, calibration: {n_mols: 0}}
    sampler: {n_samples: 10, batch_size: 4}
    metrics: {rdkit: true, novelty: true, uniqueness: true, diversity: internal_tanimoto}
    artifacts: {save_smiles: true, save_sdf: false, save_ai_scores: true}

  exp05_permuted_ai_control:
    description: "Guided run, λ=1.0, permuted AI control."
    dataset: {name: qm9_chon, split: test, limit: 0}
    seed: 42
    model: {ckpt: null, steps: 5, guidance: {enabled: true, weight: 1.0, policy: additive}}
    ai: {scorer: surrogate, surrogate_ckpt: dummy, grammar: default, mode: permuted, calibration: {n_mols: 0}}
    sampler: {n_samples: 10, batch_size: 4}
    metrics: {rdkit: true, novelty: true, uniqueness: true, diversity: internal_tanimoto}
    artifacts: {save_smiles: true, save_sdf: false, save_ai_scores: true}

  exp06_null_ai_control:
    description: "Guided run, λ=1.0, null AI control."
    dataset: {name: qm9_chon, split: test, limit: 0}
    seed: 42
    model: {ckpt: null, steps: 5, guidance: {enabled: true, weight: 1.0, policy: additive}}
    ai: {scorer: surrogate, surrogate_ckpt: dummy, grammar: default, mode: null, calibration: {n_mols: 0}}
    sampler: {n_samples: 10, batch_size: 4}
    metrics: {rdkit: true, novelty: true, uniqueness: true, diversity: internal_tanimoto}
    artifacts: {save_smiles: true, save_sdf: false, save_ai_scores: true}
