name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r env.lock
          pip install --no-cache-dir -e .
      - name: Run smoke tests
        run: pytest -q -k end_to_end
      - name: Reproducibility and integrity checks
        run: |
          python reproduce.py --smoke
          python check_integrity.py
