name: CI
on: { push: { branches: [ main ] }, pull_request: { branches: [ main ] } }
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: local/assembly:ci
          load: true
      - name: Check registry
        run: docker run --rm local/assembly:ci micromamba run -n app python scripts/check_registry.py
      - name: Run tests in container
        run: docker run --rm local/assembly:ci
